import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import FooterComponent from "@/components/organisms/footer";
import NavbarComponent from "@/components/organisms/navbar";

const poppins = Poppins({
  variable: "--font-poppins-mono",
  subsets: ["latin"],
  weight: [
    "400",
    "500",
    "600",
    "700",
  ]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins} antialiased min-h-screen`}
      >
        <NavbarComponent />
        {children}
        <FooterComponent />
      </body>
    </html>
  );
}
